apiVersion: v1
kind: Service
metadata:
  name: authorizer-loadbalancer
spec:
  selector:
    app: authorizer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Any port
      targetPort: 5000 # Same as the Deployment (in fairness, same as the Pods)